name: arcpy
channels:
  - defaults
  - conda-forge
dependencies:
  - python = 3.9
  - numpy = 1.21.6
  - scipy = 1.11.1
  - pinocchio = 3.4.0
  - pip:
    - inputs == 0.5
    - mujoco == 3.2.2
    - lcm == 1.5.1
