name: CI

on:
  push:
    branches: [ "test_ci"]
  pull_request:
    branches: [ "test_ci"]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Verify Java installation
      run: javac -version

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-version: latest
        activate-environment: arcpy
        environment-file: environment.yml
        auto-activate-base: false

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev
        # Install LCM from source
        git clone https://github.com/lcm-proj/lcm.git
        cd lcm
        mkdir build && cd build
        cmake .. -DLCM_ENABLE_EXAMPLES=OFF -DLCM_ENABLE_TESTS=OFF
        make -j$(nproc)
        sudo make install
        sudo ldconfig
        cd ../..

    - name: Generate LCM types
      shell: bash -el {0}
      run: |
        chmod +x gen_lcm_types.sh
        ./gen_lcm_types.sh

    - name: Install package
      shell: bash -el {0}
      run: |
        # Install the package in editable mode
        pip install -e . --no-deps --config-settings editable_mode=compat

    - name: Install testing and linting tools
      shell: bash -el {0}
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Check syntax errors
      shell: bash -el {0}
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run unit tests
      shell: bash -el {0}
      run: |
        pytest tests/ -v --tb=short --disable-warnings
