name: CI

on:
  push:
    branches: [ "package"]
  pull_request:
    branches: [ "package"]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-24.04, macos-latest, windows-latest]
        include:
          - os: ubuntu-24.04
            shell: bash -el {0}
            cache_path: ~/conda_pkgs_dir
            lcm_script: bash gen_lcm_types.sh
          - os: macos-latest
            shell: bash -el {0}
            cache_path: ~/conda_pkgs_dir
            lcm_script: bash gen_lcm_types.sh
          - os: windows-latest
            shell: cmd /C CALL {0}
            cache_path: D:\conda_pkgs_dir
            lcm_script: gen_lcm_types_win.cmd

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Verify Java installation
      run: javac -version

    - name: Cache conda packages
      uses: actions/cache@v3
      with:
        enableCrossOsArchive: true
        path: ${{ matrix.cache_path }}
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: ${{ runner.os }}-conda-

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-version: latest
        activate-environment: arcpy
        environment-file: environment.yml
        auto-activate-base: false
        pkgs-dirs: ${{ matrix.cache_path }}

    - name: Generate LCM types
      run: ${{ matrix.lcm_script }}

    - name: Install acr-bridge package
      run: |
        pip install -e . --no-deps --config-settings editable_mode=compat

    - name: Install testing and linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Check syntax errors
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run unit tests
      run: |
        pytest tests/ -v --tb=short --disable-warnings
