name: CI Windows

on:
  push:
    branches: [ "test_ci_win"]
  pull_request:
    branches: [ "test_ci_win"]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: cmd /C CALL {0} # Avoid `conda init` and `conda activate`

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Verify Java installation
      run: javac -version

    - name: Cache conda packages
      uses: actions/cache@v3
      with:
        enableCrossOsArchive: true
        path: D:\conda_pkgs_dir # This runs faster for cache decompression
        key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
        restore-keys: ${{ runner.os }}-conda-

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-version: latest
        activate-environment: arcpy
        environment-file: environment.yml
        auto-activate-base: false
        pkgs-dirs: D:\conda_pkgs_dir

    - name: Generate LCM types
      run: gen_lcm_types_win.cmd

    - name: Install acr-bridge package
      run: |
        pip install -e . --no-deps --config-settings editable_mode=compat

    - name: Install testing and linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Check syntax errors
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run unit tests
      run: |
        pytest tests/ -v --tb=short --disable-warnings
